### ISSUE TITLE
XML export/import

### ISSUE THREAD

**Issue by Viewline-MH** [armandomusto/Manhole-Report#24]
I can export files as an XML but I can't test the import function. If I export and then change the file name and then import, I am told that the 'project already exists do you want to overwrite it?' I thought by changing the filename it would be viewed as a different file, this is normally the case.

I tried to delete the project, in fact any project, but this brings an error message, 'constraint failed NOT NULL constraint failed:Project_Id

**Comment by armandomusto** [comment]
To test import/export you can use tablet version to export and desktop version to import. Changing the file name is not a way to import the project with a different name because each project has an unique key. When tha app recognize you are trying to import the same project it aks you to overwrite the current one. That is the standard behaviour for every software application.
